<script>
  window.storyCompliments = [
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle.",
"🌟 Senin enerjin, bulunduğun ortama neşe ve canlılık katıyor.",
"🪞 Kendine bak; aynadaki yansımada sadece yüzün değil, içindeki gücün de parlıyor.",
"🌈 Bugün, küçük bir gülümsemenin bile büyük etkiler yaratabileceği bir gün.",
"🎈 Ne zaman pes edeceğini düşündüysen, aslında en çok yaklaştığın andı.",
"🧿 Şans, sen ona inandıkça seninle kalacak bir dosttur.",
"🫧 Kalbinin derinliklerinden gelen iyilik, hayatına güzellikler çekiyor.",
"🔥 Zorluklar seni yıpratmaz, seni şekillendirir.",
"🍀 Bugün senin günün, evren seninle birlikte hareket ediyor.",
"☕ Seninle yapılan bir sohbet, insanın içini ısıtır.",
"📚 Deneyimlerin seni sen yaptı; ve sen çok güzelsin böyle."
  ];

  window.makeupCompliments = [
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor.",
"💄 Gözlerinin ışıltısı, yıldızları kıskandıracak kadar parlak.",
"👑 Kendine has tarzınla etrafına ilham veriyorsun.",
"💋 Dudaklarındaki gülümseme, bir tabloyu andırıyor.",
"👠 Attığın her adımda zarafetin yankılanıyor.",
"🌹 Bugün aynaya baktığında, gerçek güzelliğin yansımasını gör.",
"🕊 Makyajın değil; senin doğallığın ışıldıyor.",
"🪞 Kendine verdiğin değer, dışına da yansıyor.",
"✨ Teninin ışıltısı, gün ışığına meydan okuyor.",
"🎀 Güzelliğin sadece dışarıda değil, içinde de çiçek açıyor.",
"🧴 Parfümün gibi, varlığın da iz bırakıyor."
  ];
</script>