<script>
  window.storyCompliments = [
"🌟 Bu 1. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 2. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 3. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 4. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 5. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 6. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 7. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 8. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 9. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 10. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 11. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 12. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 13. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 14. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 15. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 16. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 17. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 18. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 19. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 20. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 21. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 22. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 23. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 24. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 25. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 26. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 27. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 28. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 29. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 30. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 31. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 32. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 33. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 34. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 35. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 36. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 37. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 38. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 39. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 40. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 41. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 42. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 43. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 44. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 45. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 46. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 47. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 48. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 49. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 50. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 51. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 52. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 53. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 54. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 55. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 56. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 57. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 58. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 59. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 60. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 61. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 62. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 63. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 64. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 65. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 66. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 67. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 68. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 69. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 70. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 71. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 72. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 73. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 74. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 75. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 76. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 77. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 78. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 79. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 80. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 81. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 82. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 83. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 84. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 85. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 86. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 87. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 88. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 89. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 90. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 91. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 92. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 93. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 94. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 95. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 96. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 97. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 98. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 99. cümle: Senin enerjin etrafa yayılıyor!",
"🌟 Bu 100. cümle: Senin enerjin etrafa yayılıyor!"
  ];

  window.makeupCompliments = [
"💄 Bu 1. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 2. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 3. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 4. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 5. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 6. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 7. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 8. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 9. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 10. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 11. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 12. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 13. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 14. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 15. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 16. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 17. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 18. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 19. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 20. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 21. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 22. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 23. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 24. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 25. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 26. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 27. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 28. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 29. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 30. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 31. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 32. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 33. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 34. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 35. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 36. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 37. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 38. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 39. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 40. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 41. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 42. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 43. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 44. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 45. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 46. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 47. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 48. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 49. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 50. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 51. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 52. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 53. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 54. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 55. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 56. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 57. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 58. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 59. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 60. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 61. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 62. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 63. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 64. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 65. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 66. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 67. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 68. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 69. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 70. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 71. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 72. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 73. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 74. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 75. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 76. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 77. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 78. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 79. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 80. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 81. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 82. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 83. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 84. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 85. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 86. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 87. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 88. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 89. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 90. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 91. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 92. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 93. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 94. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 95. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 96. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 97. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 98. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 99. cümle: Güzelliğin bugün bambaşka bir seviyede!",
"💄 Bu 100. cümle: Güzelliğin bugün bambaşka bir seviyede!"
  ];
</script>