const makeupCompliments = [
  "💐 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "🌸 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "💐 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "💄 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "🌸 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "🌹 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "🪞 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "👑 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "👠 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "👠 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "👠 Her halinle güzelsin, kendini kutsa.",
  "💎 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "💃 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "👠 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "💎 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "💄 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "🌸 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "💎 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "💎 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "💃 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "🪞 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "💎 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "💄 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "👑 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "💃 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "👠 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "💎 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "💃 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "💋 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "🌸 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "👠 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "💐 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "👑 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "🌹 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "🪞 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "💐 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "🌸 Her halinle güzelsin, kendini kutsa.",
  "💃 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "💄 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "💋 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "🌹 Her halinle güzelsin, kendini kutsa.",
  "💄 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "🌹 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "🪞 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "🪞 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "💄 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "👑 Her halinle güzelsin, kendini kutsa.",
  "💋 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "👠 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "💐 Her halinle güzelsin, kendini kutsa.",
  "🌹 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "💋 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "💎 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "🌹 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "💄 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "🪞 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "💐 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "💄 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "💐 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "💃 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "💎 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "👑 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "🌸 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "💐 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "💐 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "💄 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "🪞 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "💋 Her halinle güzelsin, kendini kutsa.",
  "🪞 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "🌹 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "🌸 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "👠 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "💎 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "💋 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "👑 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "💐 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "💃 Her halinle güzelsin, kendini kutsa.",
  "👑 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "💃 Doğallığın tüm güzellik anlayışlarını geride bırakıyor.",
  "🌸 Stilin kendine özgü, seni sen yapan en güzel detaylardan biri.",
  "🌸 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "👠 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "👑 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "🌹 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "💋 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "👑 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "🌸 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "💋 Zerafetin adeta bir tablo gibi, bakmaya doyamıyor insan.",
  "💋 Cildin ışıl ışıl, enerjinle uyum içinde parlıyor.",
  "💃 Çekiciliğin duruşunda gizli, çok etkileyicisin.",
  "🌹 Senin güzelliğin sadece dışarıdan değil, içten parlayan bir ışık gibi.",
  "🌹 Gözlerinde ayrı bir hikaye, dudaklarında zarafet gizli.",
  "🪞 Her halinle güzelsin, kendini kutsa.",
  "💎 Her halinle güzelsin, kendini kutsa.",
  "🪞 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "💃 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "👠 Bugün aynaya bakınca gülümse, çünkü harika görünüyorsun.",
  "💄 Her halinle güzelsin, kendini kutsa.",
  "💋 Bugün aynada gördüğün güzellik sadece bir yansıma değil, gerçeğin ta kendisi.",
  "👑 Doğallığın tüm güzellik anlayışlarını geride bırakıyor."
];