const storyCompliments = [
  "☀️ Her zaman olduğu gibi bugün de ilham vericisin.",
  "🌈 Bugün senin günün, ışığınla parlıyorsun.",
  "🌻 Her zaman olduğu gibi bugün de ilham vericisin.",
  "🌻 Her adımın umut taşıyor, farkında mısın?",
  "🌟 Küçük bir tebessümün bile büyük etkisi var.",
  "☀️ İç sesin doğru yolda olduğunu söylüyor.",
  "🌟 Seninle vakit geçirmek huzur veriyor.",
  "🕊 Küçük bir tebessümün bile büyük etkisi var.",
  "🌞 Zihnindeki dinginlik çevrene yansıyor.",
  "🕊 Bugün senin günün, ışığınla parlıyorsun.",
  "🎈 Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "💫 Seninle vakit geçirmek huzur veriyor.",
  "☀️ Varlığın bile başlı başına bir neşe kaynağı.",
  "🕊 İç sesin doğru yolda olduğunu söylüyor.",
  "🌻 Küçük bir tebessümün bile büyük etkisi var.",
  "✨ Bugün senin günün, ışığınla parlıyorsun.",
  "🌞 Küçük bir tebessümün bile büyük etkisi var.",
  "🌈 Her zaman olduğu gibi bugün de ilham vericisin.",
  "✨ Senin enerjin ortamı aydınlatıyor.",
  "✨ İç sesin doğru yolda olduğunu söylüyor.",
  "🌻 Seninle vakit geçirmek huzur veriyor.",
  "💫 İç sesin doğru yolda olduğunu söylüyor.",
  "🌟 Senin enerjin ortamı aydınlatıyor.",
  "☀️ Seninle vakit geçirmek huzur veriyor.",
  "🦋 Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "☀️ Bugün senin günün, ışığınla parlıyorsun.",
  "🎈 Her adımın umut taşıyor, farkında mısın?",
  "🎈 Seninle vakit geçirmek huzur veriyor.",
  "☀️ Senin enerjin ortamı aydınlatıyor.",
  "☀️ Küçük bir tebessümün bile büyük etkisi var.",
  "💫 Her adımın umut taşıyor, farkında mısın?",
  "💫 Küçük bir tebessümün bile büyük etkisi var.",
  "🌟 Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "💫 Varlığın bile başlı başına bir neşe kaynağı.",
  "🌞 Varlığın bile başlı başına bir neşe kaynağı.",
  "🕊 Her adımın umut taşıyor, farkında mısın?",
  "💫 Her zaman olduğu gibi bugün de ilham vericisin.",
  "🌈 Senin enerjin ortamı aydınlatıyor.",
  "☀️ Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "🌟 İç sesin doğru yolda olduğunu söylüyor.",
  "🌻 Senin enerjin ortamı aydınlatıyor.",
  "🦋 Zihnindeki dinginlik çevrene yansıyor.",
  "🎈 Varlığın bile başlı başına bir neşe kaynağı.",
  "🌻 Zihnindeki dinginlik çevrene yansıyor.",
  "🌞 Senin enerjin ortamı aydınlatıyor.",
  "🌈 Varlığın bile başlı başına bir neşe kaynağı.",
  "🕊 Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "🌟 Varlığın bile başlı başına bir neşe kaynağı.",
  "🌟 Bugün senin günün, ışığınla parlıyorsun.",
  "🌈 Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "🌻 Bugün senin günün, ışığınla parlıyorsun.",
  "🎈 Zihnindeki dinginlik çevrene yansıyor.",
  "🌟 Her zaman olduğu gibi bugün de ilham vericisin.",
  "🎈 Her zaman olduğu gibi bugün de ilham vericisin.",
  "🦋 Her adımın umut taşıyor, farkında mısın?",
  "🌞 Her zaman olduğu gibi bugün de ilham vericisin.",
  "🦋 Senin enerjin ortamı aydınlatıyor.",
  "🌞 Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "🌟 Zihnindeki dinginlik çevrene yansıyor.",
  "🦋 Bugün senin günün, ışığınla parlıyorsun.",
  "☀️ Her adımın umut taşıyor, farkında mısın?",
  "✨ Küçük bir tebessümün bile büyük etkisi var.",
  "🕊 Her zaman olduğu gibi bugün de ilham vericisin.",
  "🎈 Bugün senin günün, ışığınla parlıyorsun.",
  "💫 Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "✨ Seninle vakit geçirmek huzur veriyor.",
  "🎈 Küçük bir tebessümün bile büyük etkisi var.",
  "🕊 Seninle vakit geçirmek huzur veriyor.",
  "✨ Her adımın umut taşıyor, farkında mısın?",
  "🦋 İç sesin doğru yolda olduğunu söylüyor.",
  "🕊 Zihnindeki dinginlik çevrene yansıyor.",
  "🌻 Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "🌈 Seninle vakit geçirmek huzur veriyor.",
  "🌻 Varlığın bile başlı başına bir neşe kaynağı.",
  "💫 Bugün senin günün, ışığınla parlıyorsun.",
  "✨ Gülümsemen en karanlık günü bile güzelleştirebilir.",
  "🕊 Senin enerjin ortamı aydınlatıyor.",
  "✨ Her zaman olduğu gibi bugün de ilham vericisin.",
  "🦋 Küçük bir tebessümün bile büyük etkisi var.",
  "🌞 Her adımın umut taşıyor, farkında mısın?",
  "🌈 Küçük bir tebessümün bile büyük etkisi var.",
  "🎈 Senin enerjin ortamı aydınlatıyor.",
  "🦋 Her zaman olduğu gibi bugün de ilham vericisin.",
  "🌈 Zihnindeki dinginlik çevrene yansıyor.",
  "🎈 İç sesin doğru yolda olduğunu söylüyor.",
  "🌟 Her adımın umut taşıyor, farkında mısın?",
  "💫 Zihnindeki dinginlik çevrene yansıyor.",
  "☀️ Zihnindeki dinginlik çevrene yansıyor.",
  "🦋 Seninle vakit geçirmek huzur veriyor.",
  "🦋 Varlığın bile başlı başına bir neşe kaynağı.",
  "🌈 İç sesin doğru yolda olduğunu söylüyor.",
  "🕊 Varlığın bile başlı başına bir neşe kaynağı.",
  "🌞 Bugün senin günün, ışığınla parlıyorsun.",
  "🌈 Her adımın umut taşıyor, farkında mısın?",
  "🌻 İç sesin doğru yolda olduğunu söylüyor.",
  "🌞 İç sesin doğru yolda olduğunu söylüyor.",
  "✨ Zihnindeki dinginlik çevrene yansıyor.",
  "✨ Varlığın bile başlı başına bir neşe kaynağı.",
  "🌞 Seninle vakit geçirmek huzur veriyor.",
  "💫 Senin enerjin ortamı aydınlatıyor."
];